"""describe the change

Revision ID: 88184082df26
Revises: 11cd3f6583cb
Create Date: 2026-09-01 17:33:16.928781

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "88184082df26"
down_revision: Union[str, Sequence[str], None] = "11cd3f6583cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "simulation_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("game_id", sa.Uuid(), nullable=False),
        sa.Column("player_role", sa.String(length=32), nullable=False),
        sa.Column("run_number", sa.Integer(), nullable=False),
        sa.Column(
            "status", sa.String(length=32), server_default="ACTIVE", nullable=False
        ),
        sa.Column("rng_seed", sa.Integer(), nullable=False),
        sa.Column("events_played", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "events_played_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("current_event_id", sa.String(length=255), nullable=True),
        sa.Column(
            "state_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "event_variables", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("max_events", sa.Integer(), nullable=False),
        sa.Column("end_reason", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_simulation_runs_game_id"), "simulation_runs", ["game_id"], unique=False
    )
    op.create_index(
        "ix_simulation_runs_game_id_player_role",
        "simulation_runs",
        ["game_id", "player_role"],
        unique=False,
    )
    op.create_index(
        "ix_simulation_runs_game_id_status",
        "simulation_runs",
        ["game_id", "status"],
        unique=False,
    )
    op.create_table(
        "simulation_answers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("simulation_run_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.String(length=255), nullable=False),
        sa.Column("question_id", sa.String(length=255), nullable=False),
        sa.Column("option_id", sa.String(length=255), nullable=False),
        sa.Column("sort_index", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["simulation_run_id"], ["simulation_runs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_simulation_answers_simulation_run_id"),
        "simulation_answers",
        ["simulation_run_id"],
        unique=False,
    )
    op.create_table(
        "timeline_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("simulation_run_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("sort_index", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["simulation_run_id"], ["simulation_runs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_timeline_entries_simulation_run_id"),
        "timeline_entries",
        ["simulation_run_id"],
        unique=False,
    )
    op.add_column(
        "players",
        sa.Column("game_age", sa.Integer(), server_default="22", nullable=False),
    )
    op.add_column(
        "players",
        sa.Column(
            "game_relation_happiness",
            sa.Integer(),
            server_default="100",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("players", "game_relation_happiness")
    op.drop_column("players", "game_age")
    op.drop_index(
        op.f("ix_timeline_entries_simulation_run_id"), table_name="timeline_entries"
    )
    op.drop_table("timeline_entries")
    op.drop_index(
        op.f("ix_simulation_answers_simulation_run_id"), table_name="simulation_answers"
    )
    op.drop_table("simulation_answers")
    op.drop_index("ix_simulation_runs_game_id_status", table_name="simulation_runs")
    op.drop_index(
        "ix_simulation_runs_game_id_player_role", table_name="simulation_runs"
    )
    op.drop_index(op.f("ix_simulation_runs_game_id"), table_name="simulation_runs")
    op.drop_table("simulation_runs")
    # ### end Alembic commands ###
