"""describe the change

Revision ID: c4f52abfcfa6
Revises: 88184082df26
Create Date: 2026-09-04 20:07:56.522443

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c4f52abfcfa6"
down_revision: Union[str, Sequence[str], None] = "88184082df26"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM simulation_runs")
    op.add_column(
        "simulation_runs",
        sa.Column(
            "run_kind",
            sa.String(length=32),
            server_default="simulation",
            nullable=False,
        ),
    )
    op.add_column(
        "simulation_runs",
        sa.Column(
            "skipped_event_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("simulation_runs", "skipped_event_ids")
    op.drop_column("simulation_runs", "run_kind")
    # ### end Alembic commands ###
